config/routes.rb
Guessingame::Application.routes.draw do

  get "game" => "game#index"
  get "game/index", :as => :game
  get "game/ranking", :as => :game_ranking
  get "game/ask", :as => :game_ask
  get "game/play", :as => :game_play
  post "game/answer", :as => :game_answer

  get "rankings" => "rankings#index", :as => :ranking
  get "rankings/weekly", :as => :ranking_weekly
  get "rankings/summary", :as => :ranking_summary

  get "user/index"
  get "user/profile/:id" => "user#profile"
  get "user/search", :as => :search_user
  get "user/(:id)" => "user#show", :as => :user

  get "shop/index", :as => :shop
  post "shop/buy", :as => :shop_buy

  root :to => 'user#login'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get   '/login', :to => 'sessions#new', :as => :login
  match '/logout', :to => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  belongs_to :user
  belongs_to :matter
  attr_accessible :total_score, :user_id, :matter_id, :week_date

  # scope :weekly, lambda { find_by_sql("SELECT *, SUM(rankings.score) AS 'total_score' FROM rankings, users
  #                             WHERE users.id = rankings.user_id
  #                             AND rankings.created_at >= '#{Time.now.at_beginning_of_week}'
  #                             AND rankings.created_at <= '#{(Time.now + 1.day)}'
  #                             GROUP BY rankings.user_id
  #                             ORDER BY SUM(rankings.score) DESC") }
  # TODO: make the queries by 'scopes'

  before_save :set_the_week_date

  def set_the_week_date
    self.week_date = Time.now.at_beginning_of_week.strftime('%Y-%m-%d')
  end


  class << self

    def all_matter_weekly(date)
      find_by_sql("SELECT * FROM rankings, users
                   WHERE users.id = rankings.user_id
                   AND rankings.week_date = '#{date}'
                   GROUP BY rankings.user_id
                   ORDER BY rankings.total_score DESC")
    end

    def specific_matter_weekly(date, matter)
      find_by_sql("SELECT * FROM rankings, users
                   WHERE users.id = rankings.user_id
                   AND rankings.week_date = '#{date}'
                   AND rankings.matter = '#{matter}'
                   GROUP BY rankings.user_id
                   ORDER BY rankings.total_score DESC")
    end

    def summary(user)

      user = find_by_sql("SELECT * FROM rankings, users
                          WHERE users.id = rankings.user_id
                          AND users.id = '#{user.id}'
                          GROUP BY rankings.user_id")


      pre = find_by_sql("SELECT * FROM rankings, users
                         WHERE users.id = rankings.user_id
                         AND users.id <> '#{user.first.id}'
                         GROUP BY rankings.user_id
                         HAVING rankings.total_score >= #{user.first.score}
                         ORDER BY rankings.total_score
                         LIMIT 10")

       post = find_by_sql("SELECT * FROM rankings, users
                          WHERE users.id = rankings.user_id
                          GROUP BY rankings.user_id
                          HAVING rankings.total_score < #{user.first.score}
                          ORDER BY rankings.total_score DESC
                          LIMIT 10")

        pre.concat(user).concat(post)

    end
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController

  def index
  end

  def weekly
    @ranking = Ranking.all_matter_weekly(Time.now.at_beginning_of_week.strftime('%Y-%m-%d'))

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @ranking }
    end
  end

  def monthly
    @ranking = Ranking.monthly

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @ranking }
    end
  end

  def summary
    @ranking = Ranking.summary(@user)

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @ranking }
    end
  end

end

app/views/rankings/index.html.erb
<div id="ranking" class="ranking true">

<!-- Hide temporarily, we can't count ranking position with searching -->
<% if false %>
  <%= form_tag(search_user_path, :method => 'get') do %>
    <%= text_field_tag "search", "", :placeholder => "Search people" %>
    <%= submit_tag "Search", :class => "search" %>
  <% end %>
<% end %>

<div class="ranking-head">
  <h1>Our Ranking</h1>
  <h2>Check out how good your scores compared to scores of other players.</h2>
</div>

<% if defined?(@ranking) %>
<table border="0" cellspacing="5" cellpadding="5">
  <thead>
    <tr>
      <th>Position</th>
      <th>User</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <% @ranking.each_with_index do |user, index| %>
    <tr <%= raw 'class="you"' if user.id == @user.id %>>
      <td><%= index + 1 %></td>
      <td><%= link_to user.name, "/user/profile/#{user.id}" %></td>
      <td><%= user.total_score %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
Choose a ranking
<ul>
  <li>General</li>
  <li>Weekly</li>
</ul>
<% end %>
</div>