config/routes.rb
Guessingame::Application.routes.draw do

  get "game" => "game#index"
  get "game/index", :as => :game
  get "game/ranking", :as => :game_ranking
  get "game/ask", :as => :game_ask
  get "game/play", :as => :game_play
  post "game/answer", :as => :game_answer

  get "rankings" => "rankings#index", :as => :ranking
  get "rankings/weekly", :as => :ranking_weekly
  get "rankings/summary", :as => :ranking_summary

  get "user/index"
  get "user/profile/:id" => "user#profile"
  get "user/search", :as => :search_user
  get "user/(:id)" => "user#show", :as => :user

  get "shop/index", :as => :shop
  post "shop/buy", :as => :shop_buy

  root :to => 'user#login'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get   '/login', :to => 'sessions#new', :as => :login
  match '/logout', :to => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

end

app/controllers/shop_controller.rb
class ShopController < ApplicationController

  def index
    @specials = Special.all
  end

  # POST
  def buy
    cart = params[:available_specials].select {|key, value| params[:available_specials][key].present? }
    total = 0
    cart.each {|v,k| total += (Special.find(v).price.to_i * k.to_i) }
    puts "CART=>#{cart.inspect} - TOTAL=>#{total}"

    # Verify if the user has money to buy all items
    if @user.coins >= total
      # Buy the selected helpers
      cart.each do |s|

        special = Special.find(s.first)
        puts "Buying=>#{special.name}"
        @user.buy(special, s[1] ||= 0)
      end
      render :json => { :message => "You bought!", :coins => @user.coins }
    else
      render :json => { :message => "Inusificient cash!", :coins => @user.coins }
    end

  end

end

app/views/shop/index.html.erb
<%= javascript_tag do %>
  $(function (){
    $('.alert').hide();
    $('.buy').prop("disabled", true);

    $(".buy_special").validate({
      errorPlacement: function(error, element) { return false; },

      submitHandler: function() {
        $('span#loading').show();

        $.ajax({
          url: "<%= shop_buy_path %>.json",
          cache: false,
          dataType: 'json',
          type: 'POST',
          data: $(".buy_special").serialize(),
          success: function (data, success) {
            $('.alert').text( data.message).show();
            $(".buy_special")[0].reset();
            $("#total .cart").text("0");
            $("#total .coins").text(data.coins);
            $(".header .coins").text(data.coins);
          }
        });

      }
    });

    $(".update_total").keyup(function(){
      console.log("aisdhiasud")
      var total = 0;

      for(i = 0; i < $(".special-info").length; i++){
        var price = isNaN(parseInt($($(".special-info")[i]).find(".price").text())) ? 0 : parseInt($($(".special-info")[i]).find(".price").text());
        var qtt = isNaN(parseInt($($(".special-info")[i]).find('.update_total').val())) ? 0 : parseInt($($(".special-info")[i]).find('.update_total').val());
        total = total + (price * qtt);
      }

      if(total > <%= @user.coins.to_i %> && total != 0){
        $("#total .cart").css("color", "#AB3D39");
        $('.buy').prop("disabled", true);
      } else {
        $("#total .cart").css("color", "#FFF");
        $('.buy').prop("disabled", false);
      }
      // Update the total
      $("#total .cart").text(total);
    });
  });
<% end %>
<div class="alert">
</div>
<div id="specials" class="true">
<div id="total">
  <h1>
    $ <span class="cart">0</span> /
    $ <span class="coins"><%= @user.coins %></span>
  </h1>
  <h2>Buy specials items and get more privileges.</h2>
</div>
<% images = { 1 => "icon-time-shop.png", 2 => "icon-cut-shop.png", 3 => "icon-next-shop.png" }
description = { 1 => "Add 10 seconds to your answer time giving you more score.", 2 => "Eliminate 2 incorrect answers and maximize your successful chance.", 3 => "Jump to next question, getting the score as correct question." }
%>
<%= simple_form_for "available_specials", :html => { :class => "buy_special" } do |f| %>
  <% @specials.each do |special| %>
  <div class="special-info" id="<%= special.id %>">
    <div class="item-thumb">
    <%= image_tag images[special.id] %>
    </div>
    <h2><%= special.name %> <span>($ <span class="price"><%= special.price %></span> un.)</span></h2>
    <p>
      <%= description[special.id] %>
    </p>
    <%= f.input "#{special.id}", :required => false, :label => false, :input_html => { :class => "numeric update_total" } %>
  </div>
  <% end %>
  <%= f.submit "Buy", :class => "buy" %>
<% end %>
</div>