config/routes.rb
Guessingame::Application.routes.draw do

  get "game" => "game#index"
  get "game/index", :as => :game
  get "game/ranking", :as => :game_ranking
  get "game/ask", :as => :game_ask
  get "game/play", :as => :game_play
  post "game/answer", :as => :game_answer

  get "rankings" => "rankings#index", :as => :ranking
  get "rankings/weekly", :as => :ranking_weekly
  get "rankings/summary", :as => :ranking_summary

  get "user/index"
  get "user/profile/:id" => "user#profile"
  get "user/search", :as => :search_user
  get "user/(:id)" => "user#show", :as => :user

  get "shop/index", :as => :shop
  post "shop/buy", :as => :shop_buy

  root :to => 'user#login'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get   '/login', :to => 'sessions#new', :as => :login
  match '/logout', :to => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <a href="#">About</a> | <a href="#">How to play</a> | <a href="#">Service Terms</a> | <a href="#">Privacy Policy</a>
</div>

app/views/layouts/_header.html.erb
  <div class="header">
  <div class="true">
    <% if @user.present? %>
      <div class="top-info">
        <%= @user.name %>
        ($ <span class="coins"><%= @user.coins %></span> / <%= @user.score %> points) |
        <%= link_to 'Logout', logout_path  %>
      </div>
    <% end %>
    <div class="logo">
      <a href="/">
        <img src="/assets/logo.png" alt="Guessing Game" title="Guessing Game" />
      </a>
    </div>
    <ul>
      <li>
      <a href="<%= "/user/profile/#{@user.id}" %>" <%= "class=active" if params['controller'] == "profile" %>>Profile</a>
      </li>
      <li>
        <a href="<%= game_play_path %>" <%= "class=active" if params['controller'] == "game" %>>In Game</a>
      </li>
      <li>
        <a href="<%= ranking_summary_path %>" <%= "class=active" if params['controller'] == "rankings" %>>Ranking</a>
      </li>
      <li>
        <a href="<%= shop_path %>" <%= "class=active" if params['controller'] == "shop" %>>Shopping</a>
      </li>
    </ul>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guessinga.me</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="total">

  <header>
    <%= render 'layouts/header' %>
  </header>

  <%= yield %>

  <footer>
    <%= render 'layouts/footer' %>
  </footer>

</div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guessinga.me</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>